source 'https://supermarket.chef.io'

cookbook 'build-essential'
cookbook 'git', '~> 4.5.0'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database', '~> 5.1.2'
cookbook 'mysql', '~> 7.2.0'
cookbook 'xml'
cookbook 'ruby_build', '~> 0.8.0'
cookbook 'ruby_rbenv', '~> 1.0.1'
cookbook 'nginx', '~> 2.7.6'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'vim'
cookbook 'simple_iptables', '~> 0.7.5'
cookbook 'timezone'
