source "https://supermarket.chef.io"

cookbook 'build-essential'
cookbook 'git'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'mysql'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'rbenv', github: 'fnichol/chef-rbenv', branch: 'v0.8.0'
cookbook 'nginx'
cookbook 'imagemagick'
cookbook 'vim'
cookbook 'simple_iptables', github: 'dcrosta/cookbook-simple-iptables'
cookbook 'timezone'
