source "https://supermarket.chef.io"

cookbook 'build-essential'
cookbook 'git'
cookbook 'memcached'
cookbook 'nodejs'
cookbook 'database'
cookbook 'mysql'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'ruby_rbenv', github: 'chef-rbenv/ruby_rbenv'
cookbook 'nginx'
cookbook 'imagemagick'
cookbook 'vim'
cookbook 'simple_iptables', github: 'dcrosta/cookbook-simple-iptables'
cookbook 'timezone'
